<?php require_once 'common/inc/config.inc.php'; ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="alternate" href="<?php echo SITE_URL; ?>/terms-of-service" hreflang="en-us" />
    <link type="text/css" href="assests/css/legal-documents.css" rel="preload stylesheet" as="style"/>
    <?php require_once 'common/inc/header-files.php';?>
  </head>
  <body>
    <?php require_once 'common/inc/after-body-tag.php'; ?>
    <div class="body__wrapper">
      <div class="feature-header">
        <?php require_once 'common/header.php';?>
      </div>
      <main class="site__content">
        <section class="hero-banner">
          <div class="container">
            <div class="inner-wrap">
              <h1>Terms of Service</h1>
            </div>
          </div>
        </section>
        <section class="legal-section">
          <div class="container">
            <div class="legal_row">
              <div class="tab">
                <h2>Legal Documents</h2>
                <ul>
                <li class="tablinks active">
                <a href="terms-of-service">Terms of Service</a>
                </li>
                <li class="tablinks">
                <a href="privacy-policy">Privacy Policy</a>
                </li>
                <li class="tablinks">
                <a href="gdpr">GDPR Compliance</a>
                </li>
                <li class="tablinks">
                <a href="data-processing-agreement">Data Processing Agreement</a>
                </li>
                <li class="tablinks">
                <a href="privacy-shield-compliance">Privacy Shield Compliance</a>
                </li>
                <li class="tablinks">
                <a href="sub-processors">Sub-processors</a>
                </li>
                <li class="tablinks">
                <a href="security-reliability">Security & Reliability</a>
                </li>
                <li class="tablinks">
                <a href="refund-policy">Refund Policy</a>
                </li>
                <li class="tablinks">
                <a href="spam-guidelines">Spam Guidelines</a>
                </li>
               </ul>
              </div>
              <div id="Terms-of-service" class="tabcontent">
                <div class="tabcontent-header">
                  <h2>Terms of Service</h2>
                  <h6>Last updated: 16/08/2021</h6>
                  <p>Workstatus provides the Service to You in accordance with and subject to the following Terms of Use (these "Terms").
                  </p>
                </div>
                <div class="tabcontent-content">
                  <h3>1. Definitions</h3>
                  <p>The following definitions apply to these Terms:</p>
                  <ul>
                    <li>"Affiliate" means any entity that directly or indirectly controls, is controlled by, or is under common control with the subject entity.</li>
                    <li>"Authorized Affiliate" means any of Customer's Affiliate(s) which (a) is subject to the data protection laws and regulations of the European Union, the European Economic Area and/or their member states, Switzerland and/or the United Kingdom, and (b) is permitted to use the Services pursuant to the Agreement between Customer and Workstatus. </li>
                    <li>"Control," for purposes of this definition, means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity.</li>
                    <li>"Controller" means the natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of Personal Data; where the purposes and means of such processing are determined by the Union or Member State law, the controller of the specific criteria for its nomination may be provided for the Union or Member State law.</li>
                    <li>"Customer Data" means what is defined in the Agreement as "Customer Data" or "Your Data."</li>
                    <li>"Data Protection Laws and Regulations" means all laws and regulations, including laws and regulations of the European Union, the European Economic Area and their member states, Switzerland and the United Kingdom, applicable to the Processing of Personal Data under the Agreement.</li>
                    <li>"Data Subject" means the identified or identifiable person to whom Personal Data relates.</li>
                    <li>"Personal Data" means any information relating to (i) an identified or identifiable natural person and, (ii) an identified or identifiable legal entity (where such information is protected similarly as personal data or personally identifiable information under applicable Data Protection Laws and Regulations), where for each (i) or (ii), such data is Customer Data.</li>
                    <li>"Processing" means any operation or set of operations which is performed upon Personal Data, whether or not by automatic means, such as collection, recording, organization, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction.</li>
                    <li>"Processor" means the entity which Processes Personal Data on behalf of the Controller.</li>
                    <li>"Processor" means the entity which Processes Personal Data on behalf of the Controller. </li>
                    <li>"Project Management Application" refers to Workstatus’s web-based project management tool that allows Users to organize, assign, and track progress on tasks. </li>
                    <li>"Service" refers to all software, mobile apps, websites, and related services provided to you by Workstatus.</li>
                    <li>"Staff" refers to an individual within a User’s organization who is subject to the Staff Monitoring Application.</li>
                    <li>"Staff Monitoring Application" refers to Workstatus’s software application that allows Users to track time worked, activities, locations, and other related information for individuals within the User’s organization. The Staff Monitoring Application is one aspect of the Service provided by Workstatusunder these terms. </li>
                    <li>"Sub-processor" means any Processor engaged by Workstatus or a member of the Workstatus Group.</li>
                    <li>"Supervisory Authority" means an independent public authority which is established by an EU Member State pursuant to the GDPR.</li>
                    <li>"You," "Your," or "User" refers to anyone accessing or subject to the Service, including any Staff member, or user of the Project Management Application</li>
                  </ul>
                  <h3>2. License for use of the service; identity authentication</h3>
                  <p>The Service is licensed for use only under these Terms. Workstatus reserves all rights not expressly granted to You, including title and exclusive ownership of the Service, any and all software or updates thereto and source code for the Service.</p>
                  <p>Upon registering for the Service, Workstatus gives You the right to install the Service for use by the total number of Users You identify and authorize. The Service may not be used or accessed by (a) individuals who are not named individuals; or (b) any other software or hardware device that does not require a named individual to use or access it. A named individual means an individual identified by You by name who is authorized to use the Service, regardless of how such access occurs or if such individual uses any hardware or software that reduces the apparent number of users who are using the Service, such as by using a terminal service. The Service may not be used or accessed by any other software or hardware device that does not require an individual to use or access it. Workstatus reserves the right at any time to require You to provide a list of the named individual(s).</p>
                  <p>You may not rent, lease, lend, sell, redistribute or sublease the Service. These Terms will govern any upgrades provided by Workstatus that replace and/or supplement the original Service. You agree to use your best efforts to protect the Service and upgrades from unauthorized use, reproduction, distribution, publication or alteration.</p>
                  <h3>3.  Installation, customization, and updates</h3>
                  <p>Installation of the Service and any required modification of the Service to accommodate Your computer system must be performed by You. All updates, upgrades, enhancements and modifications to the Service MUST be performed by Workstatus. Such updates include any changes or improvements to the Service, whether arising out of the Service’s particular configuration for Your use or otherwise. At all times while these Terms are in effect, You shall provide Workstatus with access to Your computer system so that Workstatus may install all updates. Failure to allow Workstatus to install updates or to compensate Workstatus for the installation of updates automatically terminates all warranties for any purpose related to the Service as well as Your license to use the Service.</p>
                  <h3>4. Term and fees</h3>
                  <p>Provided prior notice of pricing is given to You, Workstatus reserves the right to charge You for use of the Service on a periodic (e.g., weekly or monthly) basis or otherwise. These Terms shall begin upon Your registration for the Services and shall continue until Your use of the Service is terminated by you or by Workstatus. You are responsible for all fees due to Workstatus and any compensation due to any Marketplace Member prior to the termination date.</p>
                  <h3>5. Termination</h3>
                  <p>Upon the termination of these Terms, the Service and all updates may cease to properly function and all warranties, express or implied, regarding the Service shall terminate. Your rights under these terms will automatically terminate without notice from the Workstatus if You fail to comply with any provision of these Terms. Further, Workstatus may terminate the Service for any action taken by You that Workstatus believes in its sole discretion is an inappropriate use of the Service even if not specifically detailed by these Terms, including, any use of the Service that is prohibited by federal, state, or local law. Any warranty regarding the Service will automatically terminate without notice if You fail to comply with any provision these Terms. The parties expressly acknowledge and agree that all provisions of these Terms that concern Copyright or other protectable interests of Workstatus shall remain in full force and effect notwithstanding termination of any warranty or use of the Service.</p>
                  <h3>6. Proprietary nature of the service</h3>
                  <p>The Service and Platform are proprietary to, and valuable trade secrets of Workstatus. You acknowledge the Service contains proprietary content, information and material that is protected by applicable intellectual property and other laws, including, but not limited to, copyright, trademark, and service marks, and that You will only use such proprietary content, information, or materials for permitted uses under these Terms. The Service is entrusted to You only for the purposes set forth in these Terms. You will not reverse engineer, duplicate, translate, modify, copy, printout, disassemble, decompile or otherwise tamper with the Service or any software provided therewith. The parties acknowledge that any violation of this provision will cause irreparable harm to Workstatus. As a consequence, the parties agree that if You fail to abide by these Terms, Workstatus will be entitled to specific performance, including immediate issuance of a temporary restraining order or preliminary injunction enforcing these Terms, and to judgment for damages caused by such breach, and to any other remedies provided by law.</p>
                  <h3>7. Consent to use of data</h3>
                  <p>You agree that Workstatus may collect and use technical data and User information as described in its Privacy Policy (https://Workstatus.com/privacy), and, including, but not limited to, technical information about Your device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of customization, updates, and other services to You (if any) related to the Service. Workstatus may use this information, to improve the Service or to provide services or technologies to You. Workstatus treats personally identifiable information differently from general information. Personally identifiable information can be used to identify, locate or contact You. General information is information that is not personally identifiable information and is not associated with personally identifiable information. Workstatus may convert personally identifiable information into general information by excluding information that is personally identifiable. You acknowledge that general information belongs to Workstatus and that Workstatushas the right to use such general information as it determines in its sole discretion.Workstatus may process information in the country where it was collected, as well as other countries (including the United States) where laws regarding processing of personal information may be less stringent than the laws in Your country. Workstatus uses personally identifiable information for its own internal purposes, including contacting You via email to inform you about updates to the Service and providing You with information relating to transactions that you conduct on the Workstatus’s website. Workstatus provides personally identifiable information to third parties who process it in accordance with Workstatus’s instructions in order for Workstatus to provide services to You (including processing payments for use of the Service). Workstatus reserves the right to disclose Your information if Workstatus has a good-faith belief that the disclosure is (a) required by law, regulation, or legal process; (b) appropriate to detect, prevent, or remedy violations of these Terms, fraud, security, or technical issues; or (c) permitted in order to protect Workstatus, other Users, or the public. If Workstatus is involved in a change of control through sale of assets or otherwise, we will give notice before your personally identifiable information is transferred or becomes subject to a different privacy policy.</p>
                  <h3>8. Content and linking to other websites</h3>
                  <p>The Service may enable access to the Workstatus Talent and the parties’ websites, as well as the websites of third parties (collectively, the "Websites"). The Websites may display, include, or make available content, data, information, applications or materials from third parties, including Your data, or provide links to additional third-party websites ("Data and Materials"). By using the Service, You acknowledge and agree that Workstatus is not responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright or trademark compliance, legality, decency, quality or any other aspect of the Websites. Workstatus does not warrant or endorse and does not assume and will not have any liability or responsibility to You or any other person for any data and materials on the Websites. To the extent You choose to access such Websites, You do so at Your own initiative and are responsible for compliance with any applicable laws, including, but not limited to, applicable local laws. Workstatus reserves the right to change, suspend, remove, or disable access to the Websites at any time without notice. In no event will Workstatus be liable for the removal of or disabling of access to any such Websites. Workstatus may also impose limits on the use of or access to certain Websites, in any case and without notice or liability. You agree to use the Websites at Your sole risk and that Workstatus shall not have any liability to You for content that may be found to be offensive, indecent, or objectionable.</p>
                  <h3>9. User content</h3>
                  <p>You agree that all information, data, text, sound, photographs, graphics, video, software, or other materials submitted, posted or displayed by You on or through the Service ("User Content") is your sole responsibility. Workstatus claims no ownership or control over any User Content. By submitting, posting or displaying User Content on or through the Service, you grant Workstatus a worldwide, non-exclusive, royalty-free, transferable license to use, reproduce, and adapt, such User Content to provide the Service to You. By submitting, posting or displaying User Content which is intended to be shared or made available to the general public, including through Workstatus Talent, you grant Workstatus a worldwide, non-exclusive, royalty-free license to reproduce, adapt, distribute and publish such User Content through the Service and for the purpose of promoting Workstatus and its services.</p>
                  <p>As a condition of using the Service, You agree not to use the Service to infringe the intellectual property rights of others in any way. You represent that You have the right to grant, or that the holder of any rights, including moral rights in such content has completely and effectively waived all such rights and validly and irrevocably granted to You the right to grant, the license stated above. If You post User Content in any public area of the Service, You also permit any User to access, display, view, store and reproduce such User Content for personal use. Subject to the foregoing, the owner of such User Content placed in the Service retains any and all rights that may exist in such User Content.</p>
                  <p>Workstatus may review and refuse to accept or remove any User Content in its sole discretion. Workstatus reserves the right to expel Users and prevent their further access to the Services for violating these terms or applicable laws, rules or regulations. Workstatus may take any action with respect to User Content that it deems necessary or appropriate in its sole discretion if it believes that such User Content could create liability for Workstatus, damage Workstatus’s public image or business. It is Workstatus’s policy to terminate the accounts of any Users who are repeat infringers of the copyrights, or other intellectual property rights, of others.</p>
                  <p>Any profile You submit must accurately describe You, as an individual person, or an agency or organization that you are authorized to create a profile for. Profiles derived from User Content may be made available through the Service. Workstatus does not make any representations regarding the accuracy or validity of such derived profiles, which may differ significantly from User Content.</p>
                  <h3>10. Intellectual Property Rights</h3>
                  <h4>Trademarks</h4>
                  <p>The trademarks, trade names, trade dress, logos, and service marks (collectively, the "Trademarks") displayed on www.Workstatus.com are the registered and/or unregistered Trademarks of Vinove Software & Services Pvt. LTD, or such other third party that may own the displayed Trademarks. Nothing contained on this Web site or in these terms of service grants to you, by implication or otherwise, any license or right to use any Trademarks displayed on this Web site without the written permission of Vinove Software & Services Pvt. LTD or such other third party that may own the displayed Trademarks.</p>
                  <h4>Site contents and copyright</h4>
                  <p>The text, Trademarks, logos, images, graphics, photos, video files, application functionality, or any other digital media, and their arrangement on this Website ("Website Content") are all subject to patent, copyright, trademark and other intellectual property protection. Website Content may not be copied for commercial use or redistribution, nor may Website Content be modified, processed, or reposted to other websites. Access to and uses of this Website are solely for your purchase our services or for personal use, information, education and communication with www.Workstatus.com. You may download, copy or print the Website Content of this Website for your personal non-commercial use only. No right, title or interest in any of the Website Content of this Website is transferred to you as a result of any downloading, copying, printing or use of this Website. All rights not expressly granted to you by these Terms are reserved by Workstatus.com.</p>
                  <h4>Identification of agent to receive notification of claimed copyright or trademark infringement</h4>
                  <p>If You believe that Your copyrighted work or trademark has been uploaded, posted or copied to the Service and is accessible in a way that constitutes copyright or trademark infringement, please contact Workstatus by email
                    at dave@Workstatus.com or by regular mail at:
                  </p>
                  <ol>
                    <li>Workstatus</li>
                    <li>Attn: Copyright Legal</li>
                    <li>1650 Olio Rd #1000 - 193</li>
                    <li>Fishers, IN 46037</li>
                  </ol>
                  <h3>11. Disclaimer of warranty</h3>
                  <p>You expressly acknowledge and agree that use of the service is at your sole risk. workstatus cannot and does not warrant the service will meet your requirements, that the operation of the service will be uninterrupted or error-free, or that defects in the service will be corrected. as such, you shall not rely exclusively on the service for any reason. the service and anything related thereto are provided "as is" and "as available", with all faults and without warranty of any kind, and workstatus hereby disclaims all warranties and conditions with respect to the service and anything related thereto, either express, implied or statutory, including, but not limited to, the implied warranties and/or conditions of merchantability, of satisfactory quality, of fitness for a particular purpose, of accuracy, of quiet enjoyment, and non-infringement of third party rights. no oral or written information or advice given by workstatus or its authorized representative shall create a warranty.
                  </p>
                  <h3>12. Privacy and cybersecurity indemnification</h3>
                  <p>You agree that the Workstatus Services and Platform are used to process information and Personal Data that you provide on an individual basis or by way of a transfer by a business entity under these Terms, and for purposes of these Terms you are designated the data Controller and Workstatus is designated as Processor as those terms in defined in the General Data Protection Regulation (EU) 2016/679 of the European Parliament and of the Council ("GDPR"). You further agree and acknowledge your obligations as the data Controller under the Personal Data Processing Addendum set forth below.</p>
                  <p>To the fullest extent permitted by law for all Personal Data that you collect, process via the Services or maintain on the Platform, you shall indemnify and hold Workstatus, its affiliates, and their respective officers, directors, trustees, shareholders, employees, and agents (each an "Indemnified Party"), harmless from and against any and all damages and liabilities or third party claims against any Indemnified Party, for loss, cost, damage, or expense of every kind and nature (including, without limitation, penalties imposed by law, regulations, rules by any regulatory authority, court costs, expenses, and reasonable attorneys’ fees) to the extent arising out of, relating to privacy and cybersecurity requirements, including without limitation, failure to comply with Articles 5 to 21, and 32 to 37 of the GDPR, or resulting from, in whole or in part, the breach or non-compliance with this Agreement or the omission, negligence, gross negligence or willful misconduct by you or any of your representatives.</p>
                  <h3>13. Limitation of liability</h3>
                  <p>Workstatus shall not be responsible for any loss or damage to you or any third parties caused by the service or information contained in the service. you waive any and all claims you may have against workstatus arising out of the performance or nonperformance of the service. you specifically waive any and all claims you may have against workstatus as a result of incorrect information content displayed by the service or changes to content made by you. workstatus shall not be liable for any direct, indirect, special, incidental, or consequential damage, whether based on contract or tort or any other legal theory, arising out of any use of the service or any performance of these terms, including, without limitation, damages for loss of profits, loss of data, business interruption or any other commercial damages or losses, arising out of or related to your use or inability to use the service, even if workstatus has been advised of the possibility of such damages. in no event shall workstatus’s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount actually paid by you to workstatus for the service in the 365 days immediately preceding the date that workstatus receives notice of a claim in writing from you. the foregoing limitations will apply even if the above stated remedy fails of its essential purpose.
                  </p>
                  <h3>7. Consent to electronic communications</h3>
                  <p>By registering to use the Service or Platform, or by sending us or emails, faxes, push notifications, or text or voice messages, you are communicating with us electronically. And in doing so, you expressly consent to receive communications from us electronically via email, fax, push notification, or voice or text message, whether pre-recorded or auto-dialed ("Digital Means"). We will communicate with you by the aforementioned Digital Means, or by posting notices on the Services or Platform. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. For the Services and Platform that integrate with a mobile functionality, your carrier’s normal messaging; data and other rates and fees will still apply.</p>
                  <h3>15. International users consent to cross-border transfers of personal information</h3>
                  <p>For those Workstatus users located outside the United States, you acknowledge and expressly consent to Workstatus’s use of your Personal Data and further acknowledge that Workstatus’s processing of Personal Data is required to perform the Services or use the Platform. Further at times Personal Data will be accessible by individuals who are located worldwide including in countries that the European Commission or other geopolitical authorities have not determined to provide the same level of data protection as in your country, province, territory or geopolitical region, and that such information may be accessed by the courts, law enforcement and national security authorities of such jurisdictions. By providing us with your Personal Data, you are consenting to our use of it in accordance with these Terms, including the transfer of your information across international boundaries to jurisdictions anywhere in the world as permitted by local law.</p>
                  <h3>16. No rights granted; Non-assignability</h3>
                  <p>These Terms do not constitute a grant or an intention or commitment to grant any right, title, or interest in the Service or Workstatus’s trade secrets to You. You may not sell or transfer any portion of the Service to any third party. You shall not identify the Service as coming from any source other than Workstatus. These Terms are exclusive and personal to You. You shall not assign or otherwise transfer any rights or obligations under these Terms.</p>
                  <h3>17. Miscellaneous provisions</h3>
                  <ul>
                    <li>Choice of Law. Regardless of the place of execution, delivery, performance or any other aspect of these Terms, these Terms and all of the rights of the parties under these Terms shall be governed by, construed under, and enforced in accordance with the procedural and substantive law of the State of Indiana, United States of America, to the exclusion of any conflicts or choice of law rule or principle that might otherwise refer construction or interpretation of these Terms to the substantive law of another jurisdiction. </li>
                    <li>Jurisdiction. You consent to personal jurisdiction in any of the state courts sitting in Hamilton County, Indiana, United States of America, and agree that any suit arising under these Terms shall exclusively be commenced and maintained in such courts.</li>
                    <li>General Indemnity. You agree to indemnify and hold Workstatus and (as applicable) its related entities, affiliates, and Workstatus’s and their respective officers, directors, agents, and employees, harmless from and against any and all claims, demands, proceedings, losses and damages (actual, special, and consequential) of every kind and nature, known and unknown, including reasonable attorney fees, made by any third party due to or arising out of Your breach of these Terms or Your violation of any law or the rights of any third party. </li>
                    <li>Attorney Fees and Expenses. In a dispute arising out of or related to these Terms, Workstatus shall have the right to collect reasonable attorney fees and costs and necessary expenditures from You.</li>
                    <li>Severability. If a court finds any provision of these Terms invalid or unenforceable, the remainder of these Terms shall be interpreted so as best to affect the intent of the parties.</li>
                    <li>Effect of Waiver. The failure to exercise any right provided in these Terms shall not be a waiver of prior or subsequent rights.</li>
                  </ul>
                  <h3>18. Suggestions and feedback</h3>
                  <p>Workstatus welcomes feedback or inquiries about the Service. If You elect to provide any feedback or comments of any nature to Workstatus, all feedback and comments shall be the sole and exclusive property of Workstatus, and Workstatus shall have the right to use such feedback in any manner and for any purpose in its exclusive discretion without remuneration, compensation, or attribution to you. Workstatus is under no obligation, however, to use such feedback.</p>
                  <h3>19. Refund policy</h3>
                  <p>You can cancel your account at any point in time from your organization page, or by sending an email to support@Workstatus.com with the subject line, "Cancel". We would be glad to provide further instructions at that time on how to cancel your account if needed. There will be no refunds given except for specific situations where our support team deems it necessary.</p>
                  <h3>20. Legal notice</h3>
                  <p>Workstatus may modify these Terms or any additional terms, and such modification shall be effective and binding on You upon notice by Workstatus via email to the email account provided by You upon registration for the Service. If you do not agree to any modification of these Terms, you should discontinue your use of the Service.</p>
                  <p>Communications made through the Workstatus’s website or any email or contact links provided thereon shall in no way be deemed to constitute legal notice to Workstatus or any of its officers, employees, agents, or representatives, such as where notice to Workstatus is required by contract, or any federal, state, or local laws, rules, or regulations.</p>
                  <p>You may provide notice to Workstatus at:</p>
                  <ol>
                    <li>H-221, Sector 63 Noida 201301, India</li>
                    <li>Second Floor Plot no 55 P, Sector 44 Gurugram, India</li>
                  </ol>
                  <h3>21. Minimum age of users</h3>
                  <p>All Users of Workstatus’s Service must be at least 18 years of age and older than the age of legal majority in Your jurisdiction (if it is over 18). By using the Service you promise that you are over 18 years of age and are a competent legal adult in Your jurisdiction.</p>
                  <h4>Personal data processing addendum </h4>
                  <p>This Personal Data Processing Addendum ("PDPA") addresses Personal Data Processing, privacy and cyber security obligations in addition to those expressed in the Terms as between Workstatus and Customer for subscriptions to the Workstatus Services and Platform. By agreeing to these Terms, Customer acknowledges that it and its Authorized Affiliates qualify as the "Controller" as defined under General Data Protection Regulation (EU) 2016/679 of the European Parliament and of the Council ("GDPR") to the extent that Workstatus processes Personal Data in connection with Customer’s subscription to Platform. All capitalized terms not defined in this PDPA shall have the meaning set forth in the Terms. In the course of providing the Services to Customer pursuant to the Terms, Workstatus may Process Personal Data on behalf of Customer and the Parties agree to comply with the following provisions with respect to any Personal Data.</p>
                  <h4>1. Integration</h4>
                  <p>This PDPA shall not replace any comparable or additional rights relating to Processing of Customer Data contained in the Terms.</p>
                  <h4>2. 2. Processing Of Personal Data</h4>
                  <p>2.1 Roles of the parties. The parties acknowledge and agree that with regard to the Processing of Personal Data, Customer is the Controller, Workstatus is the Processor and that Workstatus or members of the Workstatus Group will engage Sub-processors pursuant to the requirements set forth in Section 5 "Sub-processors" below.</p>
                  <p>2.2 Customer’s processing of personal data. Customer shall, in its use of the Services, Process Personal Data in accordance with the requirements of Data Protection Laws and Regulations. For the avoidance of doubt, Customer’s instructions for the Processing of Personal Data shall comply with Data Protection Laws and Regulations. Customer shall have sole responsibility for the accuracy, quality, and legality of Personal Data and the means by which Customer acquired Personal Data.</p>
                  <p>2.3 Workstatus’s processing of personal data. Workstatus shall treat Personal Data as Confidential Information and shall only Process Personal Data on behalf of and in accordance with Customer’s documented instructions for the following purposes: (i) Processing in accordance with the Terms and applicable order form(s); (ii) Processing initiated by Users in their use of the Services; and (iii) Processing to comply with other documented reasonable instructions provided by Customer (e.g., via email) where such instructions are consistent with the terms of the Agreement. </p>
                  <p>2.4 Details of the processing. The subject-matter of Processing of Personal Data by Workstatus is the performance of the Services pursuant to the Terms. The duration of the Processing, the nature and purpose of the Processing, the types of Personal Data and categories of Data Subjects Processed under this PDPA are further specified above.</p>
                  <h4>3. Rights Of Data Subjects</h4>
                  <p>3.1 Data subject request. Workstatus shall, to the extent legally permitted, promptly notify Customer if Workstatus receives a request from a Data Subject to exercise the Data Subject's right of access, right to rectification, restriction of Processing, erasure ("right to be forgotten"), data portability, object to the Processing, or its right not to be subject to an automated individual decision making ("Data Subject Request"). Taking into account the nature of the Processing, Workstatus shall assist Customer by appropriate technical and organizational measures, insofar as this is possible, for the fulfilment of Customer’s obligation to respond to a Data Subject Request under Data Protection Laws and Regulations. In addition, to the extent Customer, in its use of the Services, does not have the ability to address a Data Subject Request, Workstatus shall upon Customer’s request provide commercially reasonable efforts to assist Customer in responding to such Data Subject Request, to the extent Workstatus is legally permitted to do so and the response to such Data Subject Request is required under Data Protection Laws and Regulations. To the extent legally permitted, Customer shall be responsible for any costs arising from Workstatus’s provision of such assistance.</p>
                  <h4>4. Workstatus personnel</h4>
                  <p>4.1 Confidentiality. Workstatus shall ensure that its personnel engaged in the Processing of Personal Data are informed of the confidential nature of the Personal Data, have received appropriate training on their responsibilities and have executed written confidentiality agreements. Workstatus shall ensure that such confidentiality obligations survive the termination of the personnel engagement.</p>
                  <p>4.2 Reliability. Workstatus shall take commercially reasonable steps to ensure the reliability of any Workstatus personnel engaged in the Processing of Personal Data.</p>
                  <p>4.3 Limitation of access. Workstatus shall ensure that Workstatus’s access to Personal Data is limited to those personnel performing Services in accordance with the Agreement.</p>
                  <p>4.4 Data protection officer. Members of the Workstatus Group have appointed a data protection officer. The appointed person may be reached at jared@Workstatus.com.</p>
                  <h4>5. Sub-Processors</h4>
                  <p>5.1 Appointment of sub-processors. Customer acknowledges and agrees that (a) Workstatus’s Affiliates may be retained as Sub-processors; and (b) Workstatus and Workstatus’s Affiliates respectively may engage third-party Sub-processors in connection with the provision of the Services. Workstatus or a Workstatus Affiliate has entered into a written agreement with each Sub-processor containing data protection obligations not less protective than those in these Terms with respect to the protection of Customer Data to the extent applicable to the nature of the Services provided by such Sub-processor. </p>
                  <p>5.2 List of current sub-processors and notification of new sub-processors. Workstatus shall make available to Customer the current list of Sub-processors for the Services. Such Sub-processor lists shall include the identities of those Sub-processors and their country of location. Workstatus shall provide notification of a new Sub-processor(s) before authorizing any new Sub-processor(s) to Process Personal Data in connection with the provision of the applicable Services. </p>
                  <p>5.3 Objection right for new sub-processors. Customer may object to Workstatus’s use of a new Sub-processor by notifying Workstatus promptly in writing within ten (10) business days after receipt of Workstatus’s notice in accordance with the mechanism set out in Section 5.2. In the event Customer objects to a new Sub-processor, as permitted in the preceding sentence, Workstatus will use reasonable efforts to make available to Customer a change in the Services or recommend a commercially reasonable change to Customer’s configuration or use of the Services to avoid Processing of Personal Data by the objected-to new Sub-processor without unreasonably burdening the Customer. If Workstatus is unable to make available such change within a reasonable period of time, which shall not exceed thirty (30) days, Customer may terminate the applicable Services with respect only to those Services which cannot be provided by Workstatus without the use of the objected-to new Sub-processor by providing written notice to Workstatus. Workstatus will refund Customer any prepaid fees covering the remainder of the term of such Services following the effective date of termination with respect to such terminated Services, without imposing a penalty for such termination on Customer.</p>
                  <p>5.4 Liability. Workstatus shall be liable for the acts and omissions of its Sub-processors to the same extent Workstatus would be liable if performing the services of each Sub-processor directly under the terms of this PDPA, except as otherwise set forth in the Terms.</p>
                  <h4>6. Security</h4>
                  <p>6.1 Controls for the protection of customer data. Workstatus shall maintain appropriate technical and organizational measures for protection of the security (including protection against unauthorized or unlawful Processing and against accidental or unlawful destruction, loss or alteration or damage, unauthorized disclosure of, or access to, Customer Data), confidentiality and integrity of Customer Data, as set forth in the Security, Privacy and Architecture Documentation. Workstatus regularly monitors compliance with these measures. Workstatus will not materially decrease the overall security of the Services during a subscription term. </p>
                  <p>6.2 Third-party certifications and audits. Workstatus has obtained the third-party certifications and audits set forth in the Security, Privacy and Architecture Documentation. Upon Customer’s written request at reasonable intervals, and subject to the confidentiality obligations set forth in the Agreement, Workstatus shall make available to Customer that is not a competitor of Workstatus (or Customer’s independent, third-party auditor that is not a competitor of Workstatus) a copy of Workstatus’s then most recent third-party audits or certifications, as applicable.</p>
                  <h4>7. Customer Data Incident Management And Notification</h4>
                  <p>Workstatus maintains security incident management policies and procedures specified in the Security, Privacy and Architecture Documentation and shall, notify Customer without undue delay after becoming aware of the accidental or unlawful destruction, loss, alteration, unauthorized disclosure of, or access to Customer Data, including Personal Data, transmitted, stored or otherwise Processed by Workstatus or its Sub-processors of which Workstatus becomes aware (a "Customer Data Incident"). Workstatus shall make reasonable efforts to identify the cause of such Customer Data Incident and take those steps as Workstatus deems necessary and reasonable in order to remediate the cause of such a Customer Data Incident to the extent the remediation is within Workstatus’s reasonable control. The obligations herein shall not apply to incidents that are caused by Customer or Customer’s Users. </p>
                  <h4>8. return and deletion of customer data</h4>
                  <p>Workstatus shall return Customer Data to Customer and, to the extent allowed by applicable law, delete Customer Data in accordance with the procedures and timeframes specified in the Security and Privacy Documentation. </p>
                  <h4>9. authorized affiliates</h4>
                  <p>9.1 Contractual relationship. The parties acknowledge and agree that, by executing the Terms, the Customer enters into the PDPA on behalf of itself and, as applicable, in the name and on behalf of its Authorized Affiliates, thereby establishing a separate PDPA between Workstatus and each such Authorized Affiliate subject to the provisions of the Agreement and this Section 9 and Section 10. Each Authorized Affiliate agrees to be bound by the obligations under this PDPA and, to the extent applicable, the Agreement. For the avoidance of doubt, an Authorized Affiliate is not and does not become a party to the Terms, and is only a party to the PDPA. All access to and use of the Services and Content by Authorized Affiliates must comply with the Terms and any violation of the Terms by an Authorized Affiliate shall be deemed a violation by Customer.</p>
                  <p>9.2 Communication. The Customer that is the contracting party to Terms shall remain responsible for coordinating all communication with Workstatus under this PDPA and be entitled to make and receive any communication in relation to this PDPA on behalf of its Authorized Affiliates.</p>
                  <p>9.3 Rights of authorized affiliates. Where an Authorized Affiliate becomes a party to the PDPA with Workstatus, it shall to the extent required under applicable Data Protection Laws and Regulations be entitled to exercise the rights and seek remedies under this PDPA, subject to the following: </p>
                  <ul>
                    <li>9.3.1 Except where applicable Data Protection Laws and Regulations require the Authorized Affiliate to exercise a right or seek any remedy under this PDPA against Workstatus directly by itself, the parties agree that (i) solely the Customer that is the contracting party to the Agreement shall exercise any such right or seek any such remedy on behalf of the Authorized Affiliate, and (ii) the Customer that is the contracting party to the Terms shall exercise any such rights under this PDPA not separately for each Authorized Affiliate individually but in a combined manner for all of its Authorized Affiliates together (as set forth, for example, in Section 9.3.2, below).</li>
                    <li>9.3.2 The parties agree that the Customer that is the contracting party to the Terms and shall, when carrying out an onsite audit of the procedures relevant to the protection of Personal Data, take all reasonable measures to limit any impact on Workstatus and its Sub-Processors by combining, to the extent reasonably possible, several audit requests carried out on behalf of different Authorized Affiliates in one single audit. </li>
                  </ul>
                  <h4>10. limitation of liability</h4>
                  <p>Each party’s and all of its Affiliates’ liability, taken together in the aggregate, arising out of or related to this PDPA, and all PDPAs between Authorized Affiliates and Workstatus, whether in contract, tort or under any other theory of liability, is subject to the ‘Limitation of Liability’ section of Terms, and any reference in such section to the liability of a party means the aggregate liability of that party and all of its Affiliates under the Terms and all PDPAs together. For the avoidance of doubt, Workstatus's and its Affiliates’ total liability for all claims from the Customer and all of its Authorized Affiliates arising out of or related to the Agreement and each PDPA shall apply in the aggregate for all claims under both the Agreement and all PDPAs established under this Agreement, including by Customer and all Authorized Affiliates, and, in particular, shall not be understood to apply individually and severally to Customer and/or to any Authorized Affiliate that is a contractual party to any such PDPA. </p>
                  <h4>11. european specific provisions</h4>
                  <p>11.1 GDPR. With effect from 25 May 2018, Workstatus will Process Personal Data in accordance with the GDPR requirements directly applicable to Workstatus's provision of its Services.</p>
                  <p>11.2 Data protection impact assessment. With effect from 25 May 2018, upon Customer’s request, Workstatus shall provide Customer with reasonable cooperation and assistance needed to fulfill Customer’s obligation under the
                    GDPR to carry out a data protection impact assessment related to Customer’s use of the Services, to the extent Customer does not otherwise have access to the relevant information, and to the extent such information
                    is available to Workstatus. Workstatus shall provide reasonable assistance to Customer in the cooperation or prior consultation with the Supervisory Authority in the performance of its tasks relating to Section 11.2
                    of this PDPA, to the extent required under the GDPR.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="wsMobile whitetxt">
          <?php require_once 'common/workstatus-device.php';?>
        </section>
        <?php require_once 'common/workstatus-journey-straight.php';?>
      </main>
      <?php require_once 'common/footer.php';?>
    </div>
    <script src="assests/js/script.js"></script>
  </body>
</html>